### ISSUE TITLE
Radar bugs: grenades stays on map forever, wrong trajectory for flash

### ISSUE THREAD

**Issue by borzaka** [lexogrine/cs2-react-hud#3]
Issues:
- smokes stays on radar forever (not always)
- molotovs stays on radar forever (looks like all molotovs)
- flashes thrown from empty map location (not always)

My observations:
The radar "breaks" as soon as there are more than one grenade from the same type on the map.
For example if two molotovs used almost simultaneously, the molotovs will remain on the map.

These images way after roundEnd and even after a new round started:
- ![image](https://github.com/lexogrine/cs2-react-hud/assets/1230402/61e31494-37be-40a3-b0e3-1bcd6b5b87d4)
- ![image](https://github.com/lexogrine/cs2-react-hud/assets/1230402/5f6bf4e2-8851-460b-9645-6b5d6963064e)
- ![image](https://github.com/lexogrine/cs2-react-hud/assets/1230402/28a3b8e4-5509-456d-9f32-427f7a358ffe)
- ![image](https://github.com/lexogrine/cs2-react-hud/assets/1230402/10f4d31d-d8fd-4c0c-8e5f-ca568ae8e80c)

Errors I see in the console:
```
Warning: Encountered two children with the same key, `[object Object]_859_low`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at div
    at Radar (http://localhost:1349/dev/src/HUD/Radar/LexoRadar/LexoRadar.tsx:197:3)
    at div
    at LexoRadarContainer (http://localhost:1349/dev/src/HUD/Radar/LexoRadar/LexoRadarContainer.tsx:51:3)
    at Radar (http://localhost:1349/dev/src/HUD/Radar/Radar.tsx:19:3)
    at div
    at RadarMaps (http://localhost:1349/dev/src/HUD/Radar/RadarMaps.tsx:23:3)
    at div
    at Layout (http://localhost:1349/dev/src/HUD/Layout/Layout.tsx:37:3)
    at SettingsProvider (http://localhost:1349/dev/src/API/contexts/actions.tsx:61:3)
    at App (http://localhost:1349/dev/src/App.tsx:28:27)
```

```
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at Bomb (http://localhost:1349/dev/src/HUD/Radar/LexoRadar/LexoRadar.tsx:86:3)
    at div
    at Radar (http://localhost:1349/dev/src/HUD/Radar/LexoRadar/LexoRadar.tsx:197:3)
    at div
    at LexoRadarContainer (http://localhost:1349/dev/src/HUD/Radar/LexoRadar/LexoRadarContainer.tsx:51:3)
    at Radar (http://localhost:1349/dev/src/HUD/Radar/Radar.tsx:19:3)
    at div
    at RadarMaps (http://localhost:1349/dev/src/HUD/Radar/RadarMaps.tsx:23:3)
    at div
    at Layout (http://localhost:1349/dev/src/HUD/Layout/Layout.tsx:37:3)
    at SettingsProvider (http://localhost:1349/dev/src/API/contexts/actions.tsx:61:3)
    at App (http://localhost:1349/dev/src/App.tsx:28:27)
```

CS2 HUD version: 1.0.2
HUD Manager version: 4.8.2

**Comment by Zel1x7** [comment]
any fixes?

**Comment by Zel1xa** [comment]
Added a new pull request with a fix

**Comment by osztenkurden** [comment]
@borzaka Cant reproduce that issue, can you send over the demo that it happens on?

**Comment by osztenkurden** [comment]
Fixed with https://github.com/lexogrine/cs2-react-hud/commit/d9ecd182739a7a9893edecd9e790b2c5a39bb85e
